//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAsSQLdataSourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportSet
    {
        public int SetID { get; set; }
        public int LineNum { get; set; }
        public string Segment { get; set; }
        public string Country { get; set; }
        public string Product { get; set; }
        public string DiscountBand { get; set; }
        public Nullable<double> UnitsSold { get; set; }
        public Nullable<double> ManufacturingPrice { get; set; }
        public Nullable<double> SalesPrice { get; set; }
        public Nullable<double> GrossSales { get; set; }
        public Nullable<double> Discounts { get; set; }
        public Nullable<double> Sales { get; set; }
        public Nullable<double> COGS { get; set; }
        public Nullable<double> Profit { get; set; }
        public Nullable<System.DateTime> DateOf { get; set; }
    
        public virtual SetName SetName { get; set; }
    }
}
