//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAsSQLdataSourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SetName()
        {
            this.ImportSets = new HashSet<ImportSet>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public System.DateTime DateUploaded { get; set; }
        public Nullable<bool> HasErrors { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportSet> ImportSets { get; set; }
    }
}
