//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceQuoteDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoMake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoMake()
        {
            this.AutoModels = new HashSet<AutoModel>();
        }
    
        public int Id { get; set; }
        public string MakeName { get; set; }
        public Nullable<int> MakeRiskLevelID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoModel> AutoModels { get; set; }
        public virtual MakeRiskLevel MakeRiskLevel { get; set; }
    }
}
