//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceQuoteDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoOption()
        {
            this.Quotes = new HashSet<Quote>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AutoModelId { get; set; }
        public string OptionDescription { get; set; }
        public Nullable<short> CurbWeightLbs { get; set; }
        public Nullable<short> Horsepower { get; set; }
        public Nullable<int> PriceDollars { get; set; }
        public Nullable<int> OptionRiskLevelId { get; set; }
    
        public virtual AutoModel AutoModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual OptionRiskLevel OptionRiskLevel { get; set; }
    }
}
