//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceQuoteDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoModel()
        {
            this.Quotes = new HashSet<Quote>();
            this.AutoOptions = new HashSet<AutoOption>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AutoMakeID { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> ModelYear { get; set; }
        public Nullable<int> ModelRiskLevelID { get; set; }
    
        public virtual AutoMake AutoMake { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote> Quotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoOption> AutoOptions { get; set; }
        public virtual ModelRiskLevel ModelRiskLevel { get; set; }
    }
}
