//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceQuoteDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDrivingHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerDrivingHistory()
        {
            this.Quotes = new HashSet<Quote>();
            this.VisitorSessions = new HashSet<VisitorSession>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> NumDUIs { get; set; }
        public Nullable<int> NumSpeedingTickets { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote> Quotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitorSession> VisitorSessions { get; set; }
    }
}
