//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceQuoteDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceQuoteDBEntities : DbContext
    {
        public InsuranceQuoteDBEntities()
            : base("name=InsuranceQuoteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoModel> AutoModels { get; set; }
        public virtual DbSet<CoverageLevel> CoverageLevels { get; set; }
        public virtual DbSet<CustomerAspNetUser> CustomerAspNetUsers { get; set; }
        public virtual DbSet<CustomerDrivingHistory> CustomerDrivingHistories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AutoMake> AutoMakes { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<AutoOption> AutoOptions { get; set; }
        public virtual DbSet<MakeRiskLevel> MakeRiskLevels { get; set; }
        public virtual DbSet<ModelRiskLevel> ModelRiskLevels { get; set; }
        public virtual DbSet<OptionRiskLevel> OptionRiskLevels { get; set; }
        public virtual DbSet<Year_Make_Model_Trim_Full_Specs_by_Teoalida_SAMPLE> Year_Make_Model_Trim_Full_Specs_by_Teoalida_SAMPLE { get; set; }
        public virtual DbSet<VisitorSession> VisitorSessions { get; set; }
    }
}
