//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceQuoteDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int Id { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> AutoModelID { get; set; }
        public Nullable<int> DrivingHistoryID { get; set; }
        public Nullable<int> CoverageID { get; set; }
        public Nullable<int> AutoOptionID { get; set; }
        public Nullable<decimal> PriceQuote { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
    
        public virtual AutoModel AutoModel { get; set; }
        public virtual CoverageLevel CoverageLevel { get; set; }
        public virtual CustomerDrivingHistory CustomerDrivingHistory { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual AutoOption AutoOption { get; set; }
    }
}
