//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceQuoteDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Year_Make_Model_Trim_Full_Specs_by_Teoalida_SAMPLE
    {
        public string Make { get; set; }
        public string Model { get; set; }
        public short Year { get; set; }
        public string Trim { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<short> Curb_weight_lbs { get; set; }
        public Nullable<short> Horsepower_HP { get; set; }
    }
}
